name: oq_shared
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_avif: ^3.1.0
  flutter_cache_manager: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  nb_utils: ^7.1.8
  animate_do: ^4.2.0
  universal_io: ^2.3.1
  file_picker: ^10.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
