name: openapi
version: 1.0.0
description: OpenAPI API client
homepage: homepage

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dio: ^5.8.0+1
  freezed_annotation: ^3.1.0 # for freezed
  json_annotation: ^4.9.0
  retrofit: ^4.9.0

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.11.1
  retrofit_generator: ^10.2.0
  swagger_parser: 1.23.2
