name: project_helper
version: 1.0.0
description: OpenQuester project build helper - replaces Makefiles
homepage: https://github.com/OpenQuester/OpenQuester

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  args: ^2.6.0
  path: ^1.9.0
  yaml: ^3.1.2
  mason_logger: ^0.3.3
  cli_completion: ^0.5.1
  meta: ^1.17.0

dev_dependencies:
  lints: ^5.1.1
  build_runner: ^2.10.4

executables:
  oqhelper:
